unvmed: fix assertion when usq/ucq has q as NULL
Because of some reasons, such as qid is greater than nsqa/ncqa, there
are some cases that creating I/O SQ/CQ has failed.  However, in such
cases, the unvme object has usq/ucq instance with their `q` field as
NULL.  Because of this, when trying to travel sq/cq_list of unvme,
the assertion occurs.  By removing usq/ucq when creation has failed,
resolve this issue.

__unvme_handler: 131: msg (pid=11056): start: 'unvme create-iosq 1:0 -q 3 -z 128 -c 4'
unvme_error: 243: signal trapped (signum=6, type='Aborted')

Signed-off-by: Jonghwi Jeong <jongh2.jeong@samsung.com>